### PR TITLE
Relicense constructive measure theory

### PR DESCRIPTION
**Pull request by VincentSe**
Relicense constructive measure theory to MIT license, to be more compatible with Coq's license.

### CODE REVIEW

**Comment by spitters** [comment]
Wouldn't MIT be better going forward?

from my phone

**Comment by VincentSe** [comment]
@spitters Coq's license is LGPL 2.1 and it is not going to change. I don't see why a library of Coq would have a weaker license : when people `Require Import` a file from constructive measure theory, they also `Require Import` files from the stdlib, so using and developing constructive measure theory has the same obligations as using and developing in the stdlib.

**Comment by spitters** [comment]
I believe it was @Zimmi48 who remarked that would that choose a license again, it would be MIT, as opposed to LGPL2. Since they are compatible (as I understand), MIT seems the better choice going forward.
However, I don't feel strongly about this.

**Comment by Zimmi48** [comment]
Say one wanted to have a version of CoRN work with the HoTT library instead of the standard library. The former doesn't depend on the latter and is not under LGPL license but under a BSD2 license, which is pretty equivalent to the (more popular nowadays) MIT license. By having CoRN be distributed under LGPL, you put some additional constraints on this person, that they wouldn't have if you had chosen MIT. This is just to counter your argument about this choice being the only reasonable one since the stdlib is already under this license.

**Comment by Zimmi48** [comment]
That being said, this license issue is not very important to me TBH and, as I've said before, I'm not opposed to the use of LGPL for CoRN. It will already be more permissive if it's adopted project-wide compared to GPL.

**Comment by VincentSe** [comment]
@Zimmi48 @spitters It's MIT now. Everyone good ?

**Comment by spitters** [comment]
Yes

from my phone

**Pull request merged**
