### PR TITLE
Adapt w.r.t. coq/coq#16004.

### PR DESCRIPTION
**Pull request by ppedrot**
This should be backwards compatible up to 8.11.

### CODE REVIEW

**Comment by spitters** [comment]
@Zimmi48 Didn't you disable CI for <8.11, or was that for math-classes?
@ppedrot Thanks! However, CI fails for 8.12, 8.13 :thinking:

**Comment by Zimmi48** [comment]
No, that was math-classes. CI contains all Coq versions starting at 8.7 it seems. I have restarted the failed jobs in case it was a transient issue with Docker.

**Comment by Zimmi48** [comment]
8.10 and below then? Sure, I can do that if you want.

**Comment by spitters** [comment]
Yes, that would be great

**Pull request merged**
