### PR TITLE
Introduce meta.yml file, in place of description file.

### PR DESCRIPTION
**Pull request by Zimmi48**
Generate various files automatically.
Use standard solution for CI.
We use Nix for stable versions and opam for the development version
(it is harder to use Nix to test compatibility with moving dependencies).

### CODE REVIEW

**Comment by Zimmi48** [comment]
I don't understand the failure in the opam build: https://travis-ci.com/coq-community/corn/jobs/174931943#L2217-L2234
@erikmd Sorry to bother you with this: do you have an idea what's going on?

**Comment by erikmd** [comment]
Hi @Zimmi48, thanks for your message!
At first sight it seems that the `opam install` command lasts more than 10' (20' with `travis_retry`) without outputting anything, so Travis CI stops the job.
Could you try with `opam install -y -v -j ${NJOBS} .` instead of `opam install -y -j ${NJOBS} .`? (*without* `travis_retry` because it would be unnecessary if each individual file compile in less than 10')

**Comment by erikmd** [comment]
And if ever this wouldn't work because a given file would take 15' or 25' to compile with no warning nor any other message, one could always add a `Check true.` or so in the middle of that file…:)

**Comment by Zimmi48** [comment]
OK I've replaced the `travis_wait` with a verbose build. Let's hope this works better.

**Comment by Zimmi48** [comment]
Thanks @erikmd! Your suggestion worked.

**Pull request merged**
