### PR TITLE
Remove algebraic hierarchy from Qmetric

### PR DESCRIPTION
**Pull request by VincentSe**
Remove those 2 imports from Qmetric.v, then make the rest of CoRN compile
```
Require Import CoRN.algebra.COrdAbs.
Require Import CoRN.model.ordfields.Qordfield.
```

This aims at defining constructive real numbers abstractly, instead of relying on an algebraic hierarchy. All the similar imports will be progressively removed from folders reals/fast and reals/faster.

### CODE REVIEW

**Comment by VincentSe** [comment]
@Zimmi48 Hello, do you understand this nix error ?
`
error: unknown hash algorithm '', at /nix/store/fhksmnm8dk9b1hs99sfzha4nwvpfs86n-nixpkgs-20.09pre227892.b27a19d5bf7/nixpkgs/pkgs/build-support/fetchurl/default.nix:119:3`

It seems unrelated to the PR.

**Comment by Zimmi48** [comment]
I don't understand it (yet) but it is failing all over the place (on many projects). I will try to solve it ASAP, but if it's an issue for you, we can immediately switch to opam-based testing only.

**Comment by VincentSe** [comment]
@Zimmi48 I can wait a little. I'd like @spitters to validate this PR before we merge it.

**Comment by Zimmi48** [comment]
@VincentSe A priori this is fixed in #97 (to be confirmed when CI passes fully).

**Comment by spitters** [comment]
I'd prefer to fix it by https://github.com/coq-community/corn/pull/99 or at least have a change that does not break the type classes in our work in ODEs.

**Comment by spitters** [comment]
I've merged #97 I guess you should rebase on top of that.
Also, Travis does not seem to test 8.11, maybe we should add that.

**Comment by VincentSe** [comment]
@spitters @Zimmi48 Before Coq 8.10, the compiler doesn't resolve the Coercion
`msp_is_setoid :> RSetoid` and `st_car :> Type`. Do you know why?

This is even stranger because all previous versions compile before this pull request, so they do resolve the coercion. This confirms that Coq's implicit machinery of coercions, canonical variables and typeclasses is very fragile. What should I do ? Remove the coercion and explicitly write `st_car` everywhere needed ? I would actually consider it an improvement of the source code.

**Comment by spitters** [comment]
Yes, I was surprised about that too! Maybe @mattam82 knows what changed in the type-class implementation between these versions.

Yes, I agree inserting the st_car is the most sensible way to solve this.

**Comment by VincentSe** [comment]
@spitters @mattam82 If I remove the coercion `st_car :> Type` in `RSetoid`, that affects most of the files in CoRN. Thousands of lines of code. Since this looks like a bugfix of coercions in version 8.10, I suggest we drop compatibility before that, and add compatibility with 8.11.

**Comment by spitters** [comment]
Why would you remove the coercion? One could just insert it in the places where it cannot be found.
It looked like this failed only relatively late in the development.

I'm not opposed to dropping compatibilty with older versions, but if possible it would be nice to keep it.

**Comment by VincentSe** [comment]
@spitters @mattam82  If I add `Coercion st_car : RSetoid >-> Sortclass.` in file `UniformContinuity.v`, branch master fails with 
`Error: st_car is already a coercion.`

So how do we put the coercion back in the previous versions so that all versions compile ?

**Comment by spitters** [comment]
That the coercion fails seems to be due the the algorithm not being
clever enough.
So, you should be able to help it by just putting in st_car at these places.

No need to declare the coercion again.

**Pull request merged**
