### PR TITLE
Cut Metric.v

### PR DESCRIPTION
**Pull request by VincentSe**
Continue cutting algebraic hierarchy, and making auto proofs, typeclasses and coercions more explicit.

### CODE REVIEW

**Comment by spitters** [comment]
Could you say a bit more about this PR? Is it about cutting out the algebraic hierarchy?

**Comment by VincentSe** [comment]
@spitters Yes it continues the previous PR about the algebraic hierarchy. Also I think we can replace `Qpos` by `Q` in metric spaces, which will again simplify proofs.

**Comment by spitters** [comment]
I'm a bit hesitant to remove interesting mathematical structure (Qpos) to
solve licensing issues, but if that's needed to get the job done, maybe
it's OK.

**Comment by VincentSe** [comment]
@spitters `Qpos` is not interesting, and not necessary for metric spaces. A ball of negative radius is well-defined as the empty set, and the triangular inequality generalizes trivially in this case. If we remove `Qpos` we get rid of coercions and instances of typeclasses, which make the code more readable and more maintainable. Also backward compatibility is broken again, which illustrates yet again how fragile this implicit machinery is. The less we use it, the better.

**Comment by spitters** [comment]
I think we should learn how to improve the type class system. However,
doing this on very old code is not the most pleasant :-( So, I agree with
the way forward.

**Pull request merged**
