### PR TITLE
Remove compatibility with Coq < 8.11 and add testing for recent versions.

### PR DESCRIPTION
**Pull request by Zimmi48**

### CODE REVIEW

**Comment by Zimmi48** [comment]
Unfortunately, I couldn't enable testing with Coq 8.16 because there is no math-classes release that is compatible with it yet (fixing this might just require changing the version constraints in the opam-repository though).

**Comment by spitters** [comment]
@Zimmi48 yes, we should just do a new release for 8.16.
https://github.com/coq-community/math-classes/releases
I think the only thing that needs to be done is to write the new release notes.
I don't know if I'll find the time before the holiday though, so if you happen to beat me to it that's fine.

**Comment by Zimmi48** [comment]
@spitters Actually my point was that I don't think a new release is needed at all. I'm betting that relaxing the Coq version bounds on the latest release is sufficient. I'll open a PR trying that.

**Comment by Zimmi48** [comment]
Actually, the opam-coq-archive CI won't confirm if it works or not because it doesn't yet test Coq 8.16. However, @MSoegtropIMC should know whether math-classes is already compatible with Coq 8.16 or not (and if it isn't, he will likely open an issue asking for a new release in the coming weeks).

**Pull request merged**
