### PR TITLE
updating version number

### PR DESCRIPTION
**Pull request by spitters**

### CODE REVIEW

**Comment by Zimmi48** [comment]
@spitters This doesn't seem necessary: the current version of corn is still compatible with Coq 8.6-8.7. The problem is rather the other way around: there is no released version (tag / opam package) that is compatible with Coq 8.8. Just tagging the current master branch and publishing this on opam-coq-archive should be enough.

**Comment by spitters** [comment]
So, I just push the tag, but leave the README as it is ?

**Comment by Zimmi48** [comment]
If you want you can make the README more precise by saying that it was tested for compatibility with Coq 8.6 through 8.8.1.

**Comment by Zimmi48** [comment]
It does however require a recent math-classes. Maybe a first step would be to make a release for math-classes.

**Comment by spitters** [comment]
Done:
https://github.com/coq-community/math-classes/releases/tag/8.8.1

**Comment by Zimmi48** [comment]
Great! Now, it would probably make sense to document this requirement on the version of math-classes in the README of corn. I'll prepare the PRs on the opam archive when the tag for corn is put as well.

**Comment by spitters** [comment]
I've just updated the readme to include the version of mc

**Comment by spitters** [comment]
Since the only change is in a text file, I think we can pull, if I did not overlook anything.

**Comment by Zimmi48** [comment]
Yes

**Comment by Zimmi48** [comment]
@spitters I don't see a new tag for corn yet.

**Pull request merged**
