### PR TITLE
Add 8.10 support / testing.

### PR DESCRIPTION
**Pull request by Zimmi48**
Update to the latest versions of template, and switch opam files to 2.0.

### CODE REVIEW

**Comment by Zimmi48** [comment]
The new 8.10 testing does not work because there is no released version of math-classes that is compatible with Coq 8.10. See coq-community/math-classes#74.

**Comment by Zimmi48** [comment]
@erikmd Can you help me understand the issue here? I added a test with the Coq 8.10 Docker image, and it fails in the following way:

```
+ (/bin/bash @ line 6) $ opam pin add coq-corn . -y -n -k path
[coq-corn.dev: rsync]
[coq-corn.dev] synchronised from file:///home/coq/coq-corn
coq-corn is now pinned to file:///home/coq/coq-corn (version dev)
+ (/bin/bash @ line 7) $ opam install coq-corn -y -j 2 --deps-only
<><> Synchronising pinned packages ><><><><><><><><><><><><><><><><><><><><><><>
[coq-corn.dev] no changes from file:///home/coq/coq-corn
The following dependencies couldn't be met:
  - coq-corn -> coq >= dev
      not available because the package is pinned to version 8.10+beta2
No solution found, exiting
```

This seems weird: the opam file gives the following constraint on Coq:

```
   "coq" {(>= "8.6" & < "8.11~") | (= "dev")}
```

I would have thought that it would pick 8.10+beta2 has a version of Coq satisfying this constraint...

**Comment by erikmd** [comment]
Hi @Zimmi48, I think this is because you named the `.opam` file `corn.opam` instead of `coq-corn.opam`, so when the install is requested, opam finds the wrong specification (namely that of the repo `extra-dev`, which is loaded in the `coqorg/coq:8.10` currently because it is a pre-release).

**Comment by Zimmi48** [comment]
Right my bad! Thanks a lot.

**Comment by Zimmi48** [comment]
It looks like it worked.

**Comment by Zimmi48** [comment]
Looks like we forgot to merge this.

**Pull request merged**
