### PR TITLE
Constructive measure theory

### PR DESCRIPTION
**Pull request by VincentSe**
Implementation of constructive measure theory, as developed by Bishop and Cheng in 1972.

### CODE REVIEW

**Comment by VincentSe** [comment]
The build failed with this error
`Error: Unable to locate library ConstructiveReals.`

That probably means that CoRN is not up date with Coq's master branch, which merged this file ConstructiveReals.v 2 days ago:
https://github.com/coq/coq/pull/11725

How do we synchronize CoRN ?

**Comment by spitters** [comment]
corn depends on a stable version of coq.
In this case, I'm not sure there is other way forward than to break backwards compatibility.
@Zimmi48 do you happen to know an alternative?

**Comment by Zimmi48** [comment]
Part of @VincentSe's work on constructive reals has already been released in 8.11, but the recent PR that was merged in Coq master reorganizes most of this in different files, and if this PR depends on this reorganization, it isn't even compatible with Coq 8.11.

A temporary solution could be to enable this extension only when the detected version of Coq is >= 8.12 (this would have to be tested in the `Makefile`).

Of course, another solution would be to simply drop compatibility with all currently released versions of Coq, but in this case, we should at least ensure that a last version compatible with Coq 8.11 is released.

**Comment by VincentSe** [comment]
@Zimmi48 @spitters This PR indeed depends on Coq's reorganization PR. Acutally it was a single big PR before, that I split into 1 PR towards Coq and this PR towards CoRN.

I do not understand your explanations about the dependencies between Coq and CoRN. I expect CoRN to have several branches, that mirror Coq's versions. So branches CoRN/8.10, CoRN/8.11, CoRN/master and so on. Why is it not the case ?

CoRN is in Coq's continuous integration, so we know that it is possible to build both (and much more) on each PR.

**Comment by spitters** [comment]
Because of the close collaboration with the coqdevs we managed to keep the master version of corn compatible with many versions of Coq.
We can release an 8.11 version now, and have the master branch follow the coq master (towards 8.12) if there is no better option.

**Comment by Zimmi48** [comment]
> I do not understand your explanations about the dependencies between Coq and CoRN. I expect CoRN to have several branches, that mirror Coq's versions. So branches CoRN/8.10, CoRN/8.11, CoRN/master and so on. Why is it not the case ?

That's not how it works. CoRN has a single branch (`master`) which is tested with several versions of Coq. This is the recommendation for libraries: instead of being compatible with only one version of Coq at once, compatibility is maintained with a range of versions. This means that users can bump the version of Coq they use without changing the version of CoRN and conversely can bump the version of CoRN without changing the version of Coq (makes up for smoother upgrades).

That being said, this doesn't mean that there cannot be exceptions to this policy.

>CoRN is in Coq's continuous integration, so we know that it is possible to build both (and much more) on each PR.

Yes, and if you click on the "Details" button of the Travis failure, you can see that your PR actually did succeed with Coq master.

**Comment by VincentSe** [comment]
@Zimmi48 @spitters Ok, fair enough. In this case multi-compatibility is easy: simply do not include those 15 new files in CoRN's build when Coq's version is <= 8.11.

Do you know how to setup that in CoRN's makefile ?

**Comment by Zimmi48** [comment]
> @Zimmi48 @spitters Ok, fair enough. In this case multi-compatibility is easy: simply do not include those 15 new files in CoRN's build when Coq's version is <= 8.11.

Right!

> Do you know how to setup that in CoRN's makefile ?

No, I'm no Makefile expert. But we can ask @JasonGross for advice. He's used to this kind of tricks.

**Comment by VincentSe** [comment]
@Zimmi48 @spitters It seems that Makefile is generated by `coq_makefile -f Make -o Makefile`.

Then why is `Makefile` source-controlled in Git ? It should be deleted from Git and then git-ignored.

And then I read the doc of [coq_makefile](https://coq.inria.fr/refman/practical-tools/utilities.html), and found nothing about changing the files built in function of Coq's version.

@JasonGross Do you know another way ?

**Comment by JasonGross** [comment]
I have some code [in mit-plv/rewriter](https://github.com/mit-plv/rewriter/blob/ddb7798dd73a9a95781bd8334e92d9ff4b8a7d6e/Makefile.local.common#L10-L14) that gets the version of Coq:
```makefile
COQ_VERSION_PREFIX = The Coq Proof Assistant, version
COQ_VERSION := $(firstword $(subst $(COQ_VERSION_PREFIX),,$(shell $(COQBIN)coqc --version 2>/dev/null)))

COQ_EXTENDED_VERSION := $(shell (echo | $(COQBIN)coqtop 2>/dev/null; $(COQBIN)coqc --version 2>/dev/null))
COQ_EXTENDED_VERSION_OLD := $(shell cat $(COQ_VERSION_FILE) 2>/dev/null)
```
Then I have [some code that picks the file list based on this version](https://github.com/mit-plv/rewriter/blob/ddb7798dd73a9a95781bd8334e92d9ff4b8a7d6e/Makefile.local.common#L16-L57):
```makefile
ifneq (,$(filter 8.9%,$(COQ_VERSION)))
EXPECTED_EXT:=.v89
ML_DESCRIPTION := "Coq v8.9"
ML4_OR_MLG := ml4
else
ifneq (,$(filter 8.10%,$(COQ_VERSION)))
EXPECTED_EXT:=.v810
ML_DESCRIPTION := "Coq v8.10"
ML4_OR_MLG := mlg
else
ifneq (,$(filter 8.11%,$(COQ_VERSION)))
EXPECTED_EXT:=.v811
ML_DESCRIPTION := "Coq v8.11"
ML4_OR_MLG := mlg
else
EXPECTED_EXT:=.v812
ML_DESCRIPTION := "Coq v8.12"
ML4_OR_MLG := mlg
endif
endif
endif

COMPATIBILITY_FILES_PATTERN := \
	src/Rewriter/Util/plugins/definition_by_tactic.ml \
	src/Rewriter/Util/plugins/definition_by_tactic.mli \
	src/Rewriter/Util/plugins/definition_by_tactic_plugin.@ML4_OR_MLG@ \
	src/Rewriter/Util/plugins/definition_by_tactic_plugin.mllib \
	src/Rewriter/Util/plugins/inductive_from_elim.ml \
	src/Rewriter/Util/plugins/inductive_from_elim.mli \
	src/Rewriter/Util/plugins/inductive_from_elim_plugin.@ML4_OR_MLG@ \
	src/Rewriter/Util/plugins/inductive_from_elim_plugin.mllib \
	src/Rewriter/Util/plugins/rewriter_build.ml \
	src/Rewriter/Util/plugins/rewriter_build.mli \
	src/Rewriter/Util/plugins/rewriter_build_plugin.@ML4_OR_MLG@ \
	src/Rewriter/Util/plugins/rewriter_build_plugin.mllib \
	src/Rewriter/Util/plugins/strategy_tactic.ml \
	src/Rewriter/Util/plugins/strategy_tactic.mli \
	src/Rewriter/Util/plugins/strategy_tactic_plugin.@ML4_OR_MLG@ \
	src/Rewriter/Util/plugins/strategy_tactic_plugin.mllib \
        src/Rewriter/Util/plugins/RewriterBuildRegistry.v

COMPATIBILITY_FILES := $(subst @ML4_OR_MLG@,$(ML4_OR_MLG),$(COMPATIBILITY_FILES_PATTERN))
```
I also [generate `_CoqProject` from `_CoqProject.in` using these variables](https://github.com/mit-plv/rewriter/blob/ddb7798dd73a9a95781bd8334e92d9ff4b8a7d6e/Makefile#L39-L40) : 
```makefile
_CoqProject: _CoqProject.in
	sed s'/@ML4_OR_MLG@/$(ML4_OR_MLG)/g' $< > $@
```

Then you can just add a bit of code to the `Makefile` that generates `Makefile.coq` using `coq_makefile` and delegates to it.

**Comment by JasonGross** [comment]
Note that I also have [code that updates `$(COQ_VERSION_FILE)` only when the version of Coq changes](https://github.com/mit-plv/rewriter/blob/ddb7798dd73a9a95781bd8334e92d9ff4b8a7d6e/Makefile#L33-L37), so you can make targets depend on that file to force them to update when the version of Coq changes.

**Comment by Zimmi48** [comment]
> Then why is `Makefile` source-controlled in Git ? It should be deleted from Git and then git-ignored.

It used to be common practice. Indeed, this `coq_makefile`-generated `Makefile` supports regenerating itself. But nowadays, the recommended way is rather to wrap the call to `coq_makefile` in a small `Makefile` and to have the generated makefile be called `Makefile.coq` and be git-ignored. Cf. most other coq-community projects.

Since `Make` is also generated automatically (by `configure.sh`), a solution could also be that this is the `configure.sh` script that checks the Coq version and generate the appropriate `Make`.

**Comment by VincentSe** [comment]
@Zimmi48 @JasonGross Thanks for your ideas.

So in CoRN I propose to git-ignore `Make` and `Makefile`, because they are both generated by `configure.sh`. Then the test on Coq's version can be implemented in `configure.sh` because it's a shell script.

Does that sound right to you ?

**Comment by VincentSe** [comment]
@spitters agrees to merge. I am about to click on the merge button on github, but I remember @Zimmi48 told me not to. What's the merging process ?

**Comment by Zimmi48** [comment]
@VincentSe : that only applied to the Coq repository itself. Here you can.

**Comment by Zimmi48** [comment]
Regarding your test of the Coq version, it isn't appropriate to rely on the`+`, you should instead test that the number after the dot is >= 12.

**Comment by Zimmi48** [comment]
If I may nitpick, I should also say that your changes to `configure` could have gone in a commit separate from your gitignore changes. In any case, the commit title is misleading because this commit contains more than what's announced.

**Comment by VincentSe** [comment]
@Zimmi48 There might be a bug in `coqc --version` then. I get this

```
The Coq Proof Assistant, version 8.11+alpha (December 2019)
compiled on Dec 14 2019 12:50:03 with OCaml 4.09.0
```

and I am on this commit 

```
*   e2f0814688  (HEAD, upstream/master) Pierre-Marie Pédrot, 2 days ago | Merge PR #11647: [rfc] Consolidation of parsing interfaces
```

**Comment by Zimmi48** [comment]
As the date suggests, you probably haven't re-run `./configure` in all that time. In any case, on a fresh installation like on CI, the version will really be `8.12+alpha`.

**Comment by VincentSe** [comment]
@spitters @Zimmi48 Also, why do we exclude `tactics/Opaque_algebra.v` from the build in `configure.sh` ? If this file is not used, let's remove it.

**Comment by Zimmi48** [comment]
I have no idea. This goes far back. But that's not good practice in any case.

**Comment by spitters** [comment]
I believe it was there for performance reasons. I think it's safe to remove
now.

**Comment by VincentSe** [comment]
@Zimmi48 nitpick executed

**Pull request merged**
