### PR TITLE
Application for maintainer position

### PR DESCRIPTION
**Pull request by VincentSe**

### CODE REVIEW

**Comment by spitters** [comment]
Yes, I'd be happy to have Vincent as a co maintainer.

from my phone

**Comment by Zimmi48** [comment]
I've merged your PR and regenerated the README, but I screwed up the process a little, and this is the reason why this PR is not marked as merged. Please, never open pull request from your master branch, always use a dedicated topic branch. Otherwise, it makes collaboration on the branch much more difficult.

**Comment by Zimmi48** [comment]
@VincentSe You should have received an invitation to join coq-community, and one to join this repository as a collaborator. You only need to accept the first one, and the other one should be accepted automatically. You will then be an admin of this repository like @spitters. I've also updated the repository's description.

**Comment by VincentSe** [comment]
@Zimmi48 Done, thanks

**Pull request closed without merging**
