### PR TITLE
Overlay for PR 12287

### PR DESCRIPTION
**Pull request by VincentSe**
Replace CRzero and CRone by CR_of_Q. Temporarily disable constructive measure theory until PR 12287 is merged in Coq.

### CODE REVIEW

**Comment by VincentSe** [comment]
@Zimmi48 Those build errors are related to GTK+ and probably independent of this pull request. Can we merge ?

**Comment by spitters** [comment]
GTK+ ? is it trying to build coqide??

**Comment by Zimmi48** [comment]
The Nix package of Coq does indeed contain CoqIDE but it is not supposed to be rebuilt in the CI, a pre-compiled version is always supposed to be available. I've just checked to be sure and the same error happens on master as well. So yes, this is unrelated to this PR and is likely a recently introduced bug in nixpkgs. I'll investigate it and report it.

**Comment by VincentSe** [comment]
@Zimmi48 Thanks for the investigation.

**Pull request merged**
